services:
  - type: web
    name: exam-system-api
    env: python
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn app:app
    healthCheckPath: /api/auth/test
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///instance/app.db
      - key: ADMIN_PASSWORD
        sync: false 