"""Add invitation fields to Candidate model

Revision ID: 0fe686c9195d
Revises: 
Create Date: 2025-03-18 14:03:15.831989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe686c9195d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_invited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('last_invited_at')
        batch_op.drop_column('invitation_sent')

    # ### end Alembic commands ###
