"""add explanation column to question model

Revision ID: 706de44aab47
Revises: 0fe686c9195d
Create Date: 2025-04-06 13:38:48.435410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706de44aab47'
down_revision = '0fe686c9195d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('explanation')

    # ### end Alembic commands ###
