name: Frontend CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Lint
      run: npm run lint || echo "Linting skipped"
      
    - name: Build
      run: npm run build
      
    - name: Test
      run: npm test || echo "Tests skipped"
      
    - name: Cache build
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/cache@v3
      with:
        path: ./frontend/.next
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: ./frontend/.next
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
        
    - name: Install dependencies
      run: npm ci || npm install
        
    - name: Deploy placeholder
      run: |
        echo "Add deployment steps here when ready for production"
        # Examples:
        # - Deploy to Vercel
        # - Deploy to Netlify
        # - Deploy to GitHub Pages
        # - Build Docker image and deploy to container registry 